apiVersion: v1
kind: Service
metadata:
  name: offline-flask
  labels:
    app: offline-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: flask
  selector:
    app: offline-app

